---
# Source: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-gha-rs-no-permission
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
---
# Source: gha-runner-scale-set/templates/githubsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: arc-runner-gha-rs-github-secret
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
data:
  github_token: cGxhY2Vob2xkZXI=
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role-binding
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    arc-gha-rs-controller
  namespace: 
    arc-systems
---
# Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: arc-runner
  namespace: arc-systems
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
    actions.github.com/values-hash: 1f7e2e25cd46a1879cce3ccca83387e2ce41e747dd30ff17b6f6db794caf857
    actions.github.com/cleanup-github-secret-name: arc-runner-gha-rs-github-secret
    actions.github.com/cleanup-manager-role-binding: arc-runner-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: arc-runner-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: arc-runner-gha-rs-no-permission

spec:
  githubConfigUrl: https://github.com/example/repo
  githubConfigSecret: arc-runner-gha-rs-github-secret

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: arc-runner-gha-rs-no-permission
      containers:
      
      - name: runner
        command: 
          - /home/runner/run.sh
        image: 
          ghcr.io/actions/actions-runner:latest
